name: Build and release
on:
    workflow_dispatch:
        inputs:
            tag:
                description: 'Tag for this release'
                required: true
                type: string

jobs:
    build:
        name: Build and release
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
          - name: Checkout
            uses: actions/checkout@v4

          - name: Setup Bun
            uses: oven-sh/setup-bun@v2

          - name: Install dependencies
            run: bun install --frozen-lockfile

          - name: Build
            run: bun run build

          - name: Release
            uses: softprops/action-gh-release@v2
            env:
              GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            with:
              name: React DevTools ${{ github.event.inputs.tag }}
              tag_name: ${{ github.event.inputs.tag }}
              files: |
                dist/index.js
                dist/index.bundle